version: '3.8'

services:
  maya-cook-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ConnectionStrings__RecipesDatabase=Host=db;Database=mayaCookDb;Username=mayaUser;Password=mayaPassword

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mayaCookDb
      - POSTGRES_USER=mayaUser
      - POSTGRES_PASSWORD=mayaPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: